
name: Deploy Express API

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu for running the workflow

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY_PATH: /tmp/ec2_key.pem
      EC2_KEY: ${{ secrets.EC2_KEY }}
      APP_DIRECTORY: ${{ secrets.APP_DIRECTORY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Set up Node.js in the GitHub runner
      with:
        node-version: '20.15.1'  # Specify the Node.js version to use

    - name: Create SSH key file
      run: |
        echo "$EC2_KEY" > $EC2_KEY_PATH
        chmod 400 $EC2_KEY_PATH

    - name: Node.js Installation
      run: |
        ssh -i $EC2_KEY_PATH -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
        curl -sL https://deb.nodesource.com/setup_20.15.1 | sudo -E bash -
        sudo apt-get install -y nodejs
        node -v  # Verify installation
        npm -v   # Verify npm installation
        EOF

    - name: Copy files to EC2
      run: |
        rsync -avz --no-perms --no-times -e "ssh -i $EC2_KEY_PATH -o StrictHostKeyChecking=no" \
              --rsync-path="sudo rsync" --exclude 'public/build' --exclude 'node_modules/' \
              . $EC2_USER@$EC2_HOST:$APP_DIRECTORY

    - name: SSH into EC2 and install the dependency
      run: |
        ssh -i $EC2_KEY_PATH -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
          cd $APP_DIRECTORY
          sudo npm install
        EOF

    - name: SSH into EC2 and set up environment
      run: |
        ssh -i $EC2_KEY_PATH -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
          # Install Node.js if not already installed
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

          # Install PM2 if not already installed
          if ! command -v pm2 > /dev/null; then
            sudo npm install -g pm2
          fi

          # Navigate to the app directory
          cd $APP_DIRECTORY

          # Install production dependencies
          npm install --production

          # Start or restart the app with PM2
          pm2 start app.js --name "express-api" || pm2 restart express-api

          # Save the PM2 process list
          pm2 save
        EOF
